Algoritmo "ATIVIDADE, VARIAL PI PI"


var
        raio, perimetro, area: real
inicio
      escreva("me informe a area do seu cirulo: ")
       leia(raio)
       area <- pi * raio * raio
       perimetro <- 2 * pi * raio
       escreval("a area do seu circulo tem aproximadamente ", area," de circuferencia ")
       escreval("  ")
       escreval("o perimetro do ceu circulo tem aproximadamente ", perimetro, " de extenção ")

Fimalgoritmo