Algoritmo "PAR OU IMMPAR COM (PRECEDIMENTO(VALOR))"
Var
numero:inteiro
procedimento num(A:inteiro)
inicio

      se (A%2=0) entao
         escreval("esse é um numero par")
      senao
         escreval("esse é um numero impar")
      fimse
fimprocedimento
Inicio
      escreva("me dew um numero: ")
      leia(numero)
      num(numero)
      escreval("o valor de N é ", numero)
Fimalgoritmo