Algoritmo "SOMA DOS PROCEDIMENTOS"
Var
   X,Y:inteiro
procedimento soma(A, B: inteiro)
inicio
      A <- A + 1
      B <- B + 2
      escreval("valor de A = ", A)
      escreval("valor de B = ", B)
      escreval("soma A + B = ", A+B)
fimprocedimento
Inicio
      X <- 4
      Y <- 8
      soma(X,Y)
      escreval("Valor de X é =  ", X)
      escreval("Valor de Y é =  ", Y)
Fimalgoritmo