Algoritmo "tabuada repita"

Var
   numero, mult,multi: inteiro


Inicio
        numero <- 0
        escreval ("-------------")
        escreval ("TABUADA DE 10")
        escreval ("-------------")
        escreva ("NUMERO: ")
        leia(mult)
        repita
           numero <- numero +1
           multi <- mult * numero
           escreval(mult, " X ", numero, " = ", multi)
        ate (numero = 10)



Fimalgoritmo